### ISSUE TITLE
Some questions in Chapter 9

### ISSUE THREAD

**Issue by dayeren** [HFTrader/DeepLearningBook#15]
I do not understand the words in Section 9.7, "Note that the use of convolution for processing variable sized inputs only makes sense for inputs that have variable size because they contain varying amounts of observation of the same kind of thing—different lengths of recordings over time, different widths of observations over space, etc. Convolution does not make sense if the input has variable size because it can optionally include different kinds of observations."

It looks a little confusing about"makes sense for inputs that have variable size " and "does not make sense if the input has variable size ".

**Comment by HFTrader** [comment]
I encourage you to ask this question at 
https://groups.google.com/forum/#!forum/deeplearningbook
