### ISSUE TITLE
SSL issue: Common Name Invalid

### ISSUE THREAD

**Issue by Noah-Huppert** [HFTrader/DeepLearningBook#21]
On Chrome 57.0.2987.98 I am getting the following error when visiting www.deeplearningbook.org: `net::ERR_CERT_COMMON_NAME_INVALID`. 

The cert has a Common Name of `www.github.com` so I'm guessing something got screwed up in the Github Pages setup.

**Comment by HFTrader** [comment]
There is no need for certificate. The website was not meant to be viewed through https (secure) but http. 

try http://www.deeplearningbook.org  instead

SSL certificates are expensive and only necessary for commercial transactions

**Comment by HFTrader** [comment]
This is a non-issue

**Comment by Noah-Huppert** [comment]
Gotchya, I assumed I should access via SSL b/c a colleague shared the link with `https`, my mistake.

**Comment by recolic** [comment]
But why www.deeplearningbook.org provided a certificate for www.github.com... I'm curious about what happens.
