### ISSUE TITLE
Is there something wrong?

### ISSUE THREAD

**Issue by PANYIMING** [HFTrader/DeepLearningBook#23]
The Taylor series in Hessian matrix form seems not right,which is in the initial book 311th page.

J(θ) ≈ J(θ 0 ) + (θ − θ 0 ) ⊤ ∇ θ J(θ 0 ) +1/2 (θ − θ 0 ) ⊤ H(θ − θ 0 ),         (8.26)

**Comment by HFTrader** [comment]
Would you please ask this question here: 

https://groups.google.com/forum/#!forum/deeplearningbook

Thank you!
