### ISSUE TITLE
It is not expensive ($72) 

### ISSUE THREAD

**Issue by xpirad** [HFTrader/DeepLearningBook#24]
First of all,let me thank you for making this amazing PDF.It is really helpful.
However, there's one small issue.That is,I hope that you could change the wording of this sentence in the readme, quote"It is not expensive ($72) " .
I understand that this might be small money to you,sir.But at least to me(or,my family),$72 is really a considerable amount of money.This is about one-tenth of what my mom makes in a month.
It just makes me feel bad when reading it.
I'd really appreciate it if you could change or just delete this sentence.
Thank you again.

**Comment by HFTrader** [comment]
What are you talking about? The authors made the book free. 
And the book is cheap compared to the amount of work the authors put to write it. 
Compared to how much it can transform your career, it is dirty cheap.
I really do not care about your feelings, mate. Don't be such a child. 
Read the PDF, get a job and please buy the original.

**Comment by wildloop** [comment]
Three-month earnings in Cuba: http://www.nationmaster.com/country-info/stats/Cost-of-living/Average-monthly-disposable-salary/After-tax#amount
