### ISSUE TITLE
Embed cover into pdf

### ISSUE THREAD

**Issue by d-henderson** [HFTrader/DeepLearningBook#27]
It would be great if you could embed the cover.jpg into the pdf file into a later release. This would make it easier to locate the pdf on a phone/tablet.

**Comment by HFTrader** [comment]
This is a good idea.  I just dont know how to do it, perhaps hacking into the PDF code would be easier.  I will leave this here for someone to weigh in. Thanks for the idea.

**Comment by AdityaSoni19031997** [comment]
Step1

Open your e-book PDF. Select "Document," "Pages" and then "Insert." Go to "Insert Dialogue" and click "Select." Select your jpeg cover image. Choose where in the e-book file you want your cover graphic to appear, when the "Insert Pages Dialogue" box appears. Choose the option to have the cover graphic appear first in the document, and ti will become the first page.

Step 2

Open the "Location" drop-down list and click "Before" and then "OK." This will move your cover image from the first page to the actual cover location of your book. Verify the location of the cover graphic by clicking the "Pages Palette" tab.

Step 3

Change the cover image from being listed as page one by selecting "Number Pages" from the "Option" menu at the top of the "Pages Palette." Insert an inside front cover page; this page can be blank, if you like. By inserting an inside front cover, you ensure that your cover image cannot revert to the first page

**Comment by HFTrader** [comment]
The intention is not to make a perfect copy of the book, just make it convenient to read. 
I would really encourage you to BUY the book in digital format if you want an up-to-date version with a much better presentation and less typos.
Then kindle version is just $64 and the hardcover version dropped from $72 to a meager $54, which is less than a rock concert ticket or an Xbox controller.
