### ISSUE TITLE
Copyright issue?

### ISSUE THREAD

**Issue by nextofsearch** [HFTrader/DeepLearningBook#28]
Hi,

The FAQ in the home page (http://www.deeplearningbook.org/) clearly states that they can't distribute the content in PDF format due to their contract with MIT press.

> Can I get a PDF of this book?
> No, our contract with MIT Press forbids distribution of too easily copied electronic formats of the book.
> 

How come you distribute this in PDF format? Did you get a permission for it?

**Comment by HFTrader** [comment]
Yes, the author has been asked about this on a Reddit AMA and he says that while he cannot distribute himself a PDF (his contract does not allow HIM), there is nothing legally against others distributing the text in PDF format, as it was released free to the public.

**Comment by nextofsearch** [comment]
@HFTrader Can you give me a link to the thread on Reddit AMA with the author's comment? I searched for it but I couldn't find it.
