### ISSUE TITLE
If has a latex version , it is better

### ISSUE THREAD

**Issue by AnddyWang** [HFTrader/DeepLearningBook#9]
If has a latex version , it is better

**Comment by AnddyWang** [comment]
If has a latex version , it is better

**Comment by AnddyWang** [comment]
up

**Comment by AnddyWang** [comment]
please release a latex version,thanks very much

**Comment by HFTrader** [comment]
This PDF is a convenience made from the original book available at http://www.deeplearningbook.org/.

**Comment by madduci** [comment]
I suggest to use Asciidoc. You can maintain both HTML and PDF
